name = "agent"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "d4788f1fc05bad3323aa34314e35d891"

[vars]
DEFAULT_MODEL = "qwen3.5-plus"

[observability]
enabled = true
head_sampling_rate = 1
