import express from "express";
import cors from "cors";
import OpenAI from "openai";

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 3001;

const SYSTEM_PROMPT = `You are an autonomous AI agent capable of performing complex tasks. You have access to tools for:
- Searching the web for real-time information
- Writing and explaining code in any language
- Creating detailed step-by-step plans
- Analyzing and summarizing content
- Browsing URLs and extracting information

When given a task, think step by step. Use your tools when needed to complete the task thoroughly. Be precise, efficient, and always deliver results. Show your reasoning and tool usage transparently.`;

const tools = [
  {
    type: "function",
    function: {
      name: "search_web",
      description: "Search the internet for real-time information, news, or facts about any topic.",
      parameters: {
        type: "object",
        properties: {
          query: { type: "string", description: "The search query" },
          reason: { type: "string", description: "Why you need this information" }
        },
        required: ["query", "reason"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "write_code",
      description: "Write, analyze, debug, or explain code in any programming language.",
      parameters: {
        type: "object",
        properties: {
          language: { type: "string", description: "Programming language" },
          task: { type: "string", description: "What the code should do" },
          existing_code: { type: "string", description: "Existing code to modify/debug (optional)" }
        },
        required: ["language", "task"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "browse_url",
      description: "Visit a URL and extract information from a webpage.",
      parameters: {
        type: "object",
        properties: {
          url: { type: "string", description: "The URL to browse" },
          goal: { type: "string", description: "What information to extract" }
        },
        required: ["url", "goal"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "create_plan",
      description: "Break down a complex goal into actionable steps with a timeline.",
      parameters: {
        type: "object",
        properties: {
          goal: { type: "string", description: "The goal to plan for" },
          context: { type: "string", description: "Additional context" }
        },
        required: ["goal"]
      }
    }
  }
];

function simulateToolResult(toolName, args) {
  switch (toolName) {
    case "search_web":
      return JSON.stringify({
        results: [
          { title: `Search: ${args.query}`, snippet: `Found relevant information about "${args.query}". The AI agent has processed this query and gathered contextual data from multiple sources.`, url: `https://search.example.com/q=${encodeURIComponent(args.query)}` },
          { title: `Latest on: ${args.query}`, snippet: `Recent updates and comprehensive analysis regarding ${args.query}. Multiple sources confirm the key details.`, url: `https://news.example.com/${encodeURIComponent(args.query)}` }
        ],
        query: args.query,
        timestamp: new Date().toISOString()
      });
    case "browse_url":
      return JSON.stringify({
        url: args.url,
        content: `Successfully accessed ${args.url}. Extracted information relevant to: "${args.goal}". The page contains structured data that has been processed and analyzed by the agent.`,
        status: 200
      });
    case "create_plan":
      return JSON.stringify({
        goal: args.goal,
        created: new Date().toISOString(),
        note: "Plan will be generated by the AI based on the goal"
      });
    case "write_code":
      return JSON.stringify({
        language: args.language,
        task: args.task,
        note: "Code will be written by the AI based on the task"
      });
    default:
      return JSON.stringify({ status: "completed" });
  }
}

app.get("/api/health", (req, res) => {
  res.json({ ok: true, time: new Date().toISOString() });
});

app.post("/api/agent", async (req, res) => {
  const { message, history = [], apiKey } = req.body;

  if (!message) {
    return res.status(400).json({ error: "Message is required" });
  }

  const key = apiKey || process.env.OPENAI_API_KEY;
  if (!key) {
    return res.status(401).json({ error: "OpenAI API key required. Please add your API key in settings." });
  }

  const openai = new OpenAI({ apiKey: key });

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");

  const send = (data) => res.write(`data: ${JSON.stringify(data)}\n\n`);

  try {
    const messages = [
      { role: "system", content: SYSTEM_PROMPT },
      ...history,
      { role: "user", content: message }
    ];

    let continueLoop = true;

    while (continueLoop) {
      const stream = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages,
        tools,
        tool_choice: "auto",
        stream: true,
        temperature: 0.7,
        max_tokens: 2000
      });

      let fullContent = "";
      let toolCalls = [];
      let currentToolCall = null;

      for await (const chunk of stream) {
        const delta = chunk.choices[0]?.delta;
        const finishReason = chunk.choices[0]?.finish_reason;

        if (delta?.content) {
          fullContent += delta.content;
          send({ type: "text", content: delta.content });
        }

        if (delta?.tool_calls) {
          for (const tc of delta.tool_calls) {
            if (tc.index !== undefined) {
              if (!toolCalls[tc.index]) {
                toolCalls[tc.index] = { id: tc.id || "", type: "function", function: { name: "", arguments: "" } };
              }
              if (tc.id) toolCalls[tc.index].id = tc.id;
              if (tc.function?.name) toolCalls[tc.index].function.name += tc.function.name;
              if (tc.function?.arguments) toolCalls[tc.index].function.arguments += tc.function.arguments;
            }
          }
        }

        if (finishReason === "tool_calls") {
          messages.push({ role: "assistant", content: fullContent || null, tool_calls: toolCalls });

          for (const tc of toolCalls) {
            let args = {};
            try { args = JSON.parse(tc.function.arguments); } catch {}

            send({ type: "tool_start", tool: tc.function.name, args, id: tc.id });

            await new Promise(r => setTimeout(r, 600));

            const result = simulateToolResult(tc.function.name, args);
            send({ type: "tool_end", tool: tc.function.name, result: JSON.parse(result), id: tc.id });

            messages.push({ role: "tool", tool_call_id: tc.id, content: result });
          }

          toolCalls = [];
          fullContent = "";
        }

        if (finishReason === "stop") {
          continueLoop = false;
          messages.push({ role: "assistant", content: fullContent });
        }
      }
    }

    send({ type: "done" });
    res.end();
  } catch (err) {
    console.error("Agent error:", err.message);
    send({ type: "error", message: err.message });
    res.end();
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`AI Agent server running at http://localhost:${PORT}`);
});
